import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const SOURCE_DIR = path.join(
  ROOT,
  "custom_components",
  "vikunja",
  "frontend",
  "translations",
);
const OUTPUT = path.join(
  ROOT,
  "custom_components",
  "vikunja",
  "frontend",
  "vikunja-todo-card-translations.js",
);
const EXPECTED_LOCALES = [
  "ar", "bn", "de", "el", "en", "es", "fa", "fr", "ga", "hi", "hu",
  "id", "it", "ja", "ko", "nl", "pl", "pt", "ro", "ru", "sr", "th",
  "tr", "uk", "ur", "vi", "zh",
];

function sortedKeys(value) {
  return Object.keys(value).sort();
}

const translations = {};
for (const locale of EXPECTED_LOCALES) {
  const filename = path.join(SOURCE_DIR, `${locale}.json`);
  translations[locale] = JSON.parse(fs.readFileSync(filename, "utf8"));
}

const actualFiles = fs
  .readdirSync(SOURCE_DIR)
  .filter((filename) => filename.endsWith(".json"))
  .map((filename) => filename.slice(0, -5))
  .sort();
if (JSON.stringify(actualFiles) !== JSON.stringify(EXPECTED_LOCALES)) {
  throw new Error("Card translation files do not match the supported locale list");
}

const englishKeys = sortedKeys(translations.en);
for (const [locale, values] of Object.entries(translations)) {
  if (JSON.stringify(sortedKeys(values)) !== JSON.stringify(englishKeys)) {
    throw new Error(`${locale}.json does not match the English translation keys`);
  }
  for (const [key, value] of Object.entries(values)) {
    if (typeof value !== "string" || !value.trim()) {
      throw new Error(`${locale}.${key} must be a non-empty string`);
    }
  }
}

const output = `// Generated by scripts/build_card_translations.mjs. Do not edit directly.\nexport const TRANSLATIONS = ${JSON.stringify(translations, null, 2)};\n`;
if (process.argv.includes("--check")) {
  if (!fs.existsSync(OUTPUT) || fs.readFileSync(OUTPUT, "utf8") !== output) {
    throw new Error("Generated card translations are out of date");
  }
} else {
  fs.writeFileSync(OUTPUT, output, "utf8");
}
